<?php

/**
 * @file
 * Handles the creation/display of islandora:html_snippet objects.
 */

/**
 * Implements hook_menu().
 */
function islandora_html_snippet_menu() {
  return array(
    'admin/islandora/solution_pack_config/html_snippet' => array(
      'title' => 'HTML Snippet Pack',
      'description' => 'Define ingest behavior and configure preview display.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('islandora_html_snippet_admin'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
    'islandora/object/%islandora_object/manage/object/html_snippet/edit' => array(
      'title' => t('Edit HTML Content'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_html_snippet_html_edit_form', 2),
      'access callback' => 'islandora_object_manage_access_callback',
      'access arguments' => array(
        array(
          ISLANDORA_MANAGE_PROPERTIES,
          ISLANDORA_METADATA_EDIT,
          ISLANDORA_ADD_DS,
        ), 2),
      'file' => 'includes/html_snippet_edit.form.inc',
      'type' => MENU_CALLBACK,
    ),
  );
}

/**
 * Implements hook_islandora_edit_datastream_registry().
 */
function islandora_html_snippet_islandora_edit_datastream_registry(AbstractObject $object, AbstractDatastream $datastream) {
  if (($datastream->id == 'OBJ') AND in_array('islandora:sp_html_snippet', $object->models)) {
    return array(
      array(
        'Name' => t('Edit HTML Content'),
        'url' => "islandora/object/{$object->id}/manage/object/html_snippet/edit",
        'weight' => 5,
      ),
    );
  }
}


/**
 * Implements hook_theme().
 */
function islandora_html_snippet_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_html_snippet' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-html-snippet',
      'pattern' => 'islandora_html_snippet__',
      'variables' => array('islandora_object' => NULL),
    ),
    'islandora_html_snippet_print' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-html-snippet-print',
      'pattern' => 'islandora_html_snippet_print__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_html_snippet_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_html_snippet');
  // HTML Snippet Content Model.
  $html_snippet_content_model = $connection->repository->constructObject('islandora:sp_html_snippet');
  $html_snippet_content_model->owner = 'fedoraAdmin';
  $html_snippet_content_model->label = 'Islandora HTML Snippet Content Model';
  $html_snippet_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $html_snippet_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'application/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_html_snippet_ds_composite_model.xml", FALSE);
  $html_snippet_content_model->ingestDatastream($datastream);
  // HTML Snippet Collection.
  $html_snippet_collection = $connection->repository->constructObject('islandora:sp_html_snippet_collection');
  $html_snippet_collection->owner = 'fedoraAdmin';
  $html_snippet_collection->label = 'HTML Snippet Collection';
  $html_snippet_collection->models = 'islandora:collectionCModel';
  $html_snippet_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $html_snippet_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'application/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_html_snippet_collection_policy.xml", FALSE);
  $html_snippet_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $html_snippet_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $html_snippet_collection->ingestDatastream($datastream);
  return array(
    'islandora_html_snippet' => array(
      'title' => 'Islandora HTML Snippet',
      'objects' => array(
        $html_snippet_content_model,
        $html_snippet_collection,
      ),
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_html_snippet_islandora_sp_html_snippet_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_html_snippet', array('islandora_object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_islandora_view_print_object().
 */
function islandora_html_snippet_islandora_view_print_object($object) {
  $output = theme('islandora_html_snippet_print', array('islandora_object' => $object));
  return array('html' => $output);
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_html_snippet_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_html_snippet');
  return array(
    'HTML Snippet MODS form' => array(
      'form_file' => "$module_path/xml/islandora_html_snippet_mods_form.xml",
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_form_associations().
 */
function islandora_html_snippet_islandora_xml_form_builder_form_associations() {
  return array(
    'islandora_html_snippet_mods_form' => array(
      'content_model' => 'islandora:sp_html_snippet',
      'form_name' => 'HTML Snippet MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_html_snippet_islandora_sp_html_snippet_islandora_ingest_steps() {
  return array(
    'islandora_html_snippet_edit' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_html_snippet_html_edit_form',
      'module' => 'islandora_html_snippet',
      'file' => 'includes/html_snippet_edit.form.inc',
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_derivative().
 */
function islandora_html_snippet_islandora_sp_html_snippet_islandora_derivative() {
  $derivatives = array();
  return $derivatives;
}
